spring.application.name=MVC_Demo

# Tymczasowo wylacza inicjalizacje repozytoriow JPA (projekt demonstracyjny bez kompletnej encji).
# spring.data.jpa.repositories.enabled=false

spring.datasource.url=jdbc:h2:file:./testdb
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
